### ISSUE TITLE
yarn install

### ISSUE THREAD

**Issue by kivervinicius** [JulienRioux/flawwwless-ui#4]
[!] Error: Could not resolve './Navbar.css' from src/components/Navbar/index.js
Error: Could not resolve './Navbar.css' from src/components/Navbar/index.js
    at error (/projetos/react/flawwwless-ui/node_modules/rollup/dist/rollup.js:3365:15)
    at /projetos/react/flawwwless-ui/node_modules/rollup/dist/rollup.js:21504:25

**Comment by tuantvk** [comment]
@kivervinicius fixed in [PR#6](https://github.com/JulienRioux/flawwwless-ui/pull/6)
